In [1]:
import pandas as pd
import geopandas as gpd

In [2]:
ncCurrent = gpd.read_file("./nc-boundary-2019.json")

In [3]:
ncCurrent.head()

,name,waddress,certified,objectid,service_re,nc_id,dwebsite,geometry
0,LINCOLN HEIGHTS NC,http://www.lincolnheightsnc.org/,2002-04-27T00:00:00,1,REGION 8 - NORTH EAST LA,47,http://empowerla.org/LHNC,"MULTIPOLYGON (((-118.20503 34.05558, -118.2060..."
1,VOICES OF 90037,None,2008-06-16T00:00:00,2,REGION 9 - SOUTH LA 2,109,http://empowerla.org/VOICESOF90037,"MULTIPOLYGON (((-118.28273 34.01114, -118.2823..."
2,LOS FELIZ NC,http://www.losfeliznc.org/,2002-06-11T00:00:00,3,REGION 7 - EAST,36,http://empowerla.org/LFNC,"MULTIPOLYGON (((-118.30027 34.15793, -118.2988..."
3,MISSION HILLS NC,http://mhnconline.org/,2005-04-19T00:00:00,4,REGION 1 - NORTH EAST VALLEY,101,http://empowerla.org/MHNC,"MULTIPOLYGON (((-118.46933 34.28050, -118.4693..."
4,GREATER TOLUCA LAKE NC,http://www.gtlnc.org/,2002-09-10T00:00:00,5,REGION 4 - SOUTH EAST VALLEY,28,http://empowerla.org/GTLNC,"MULTIPOLYGON (((-118.35520 34.16491, -118.3552..."

In [8]:
ncCurrent['id'] = ncCurrent['nc_id'].astype(int)

In [9]:
NCdf = pd.DataFrame(ncCurrent)
NCdf.set_index([ 'id'], inplace=True)

In [10]:
NCdf.head()

,name,waddress,certified,objectid,service_re,nc_id,dwebsite,geometry
id,,,,,,,,
47,LINCOLN HEIGHTS NC,http://www.lincolnheightsnc.org/,2002-04-27T00:00:00,1,REGION 8 - NORTH EAST LA,47,http://empowerla.org/LHNC,"MULTIPOLYGON (((-118.20503 34.05558, -118.2060..."
109,VOICES OF 90037,None,2008-06-16T00:00:00,2,REGION 9 - SOUTH LA 2,109,http://empowerla.org/VOICESOF90037,"MULTIPOLYGON (((-118.28273 34.01114, -118.2823..."
36,LOS FELIZ NC,http://www.losfeliznc.org/,2002-06-11T00:00:00,3,REGION 7 - EAST,36,http://empowerla.org/LFNC,"MULTIPOLYGON (((-118.30027 34.15793, -118.2988..."
101,MISSION HILLS NC,http://mhnconline.org/,2005-04-19T00:00:00,4,REGION 1 - NORTH EAST VALLEY,101,http://empowerla.org/MHNC,"MULTIPOLYGON (((-118.46933 34.28050, -118.4693..."
28,GREATER TOLUCA LAKE NC,http://www.gtlnc.org/,2002-09-10T00:00:00,5,REGION 4 - SOUTH EAST VALLEY,28,http://empowerla.org/GTLNC,"MULTIPOLYGON (((-118.35520 34.16491, -118.3552..."

In [11]:
test = NCdf.loc[NCdf['name'] == 'NORTH WESTWOOD']
print(test)

Empty DataFrame
Columns: [name, waddress, certified, objectid, service_re, nc_id, dwebsite, geometry]
Index: []

In [12]:
councils = [
  {
    'id': 6,
    'name': 'Arleta',
    'region': 'North East Valley',
  },
  {
    'id': 9,
    'name': 'Foothill Trails District',
    'region': 'North East Valley',
  },
  {
    'id': 101,
    'name': 'Mission Hills',
    'region': 'North East Valley',
  },
  {
    'id': 112,
    'name': 'North Hills East',
    'region': 'North East Valley',
  },
  {
    'id': 7,
    'name': 'Pacoima',
    'region': 'North East Valley',
  },
  {
    'id': 100,
    'name': 'Panorama City',
    'region': 'North East Valley',
  },
  {
    'id': 8,
    'name': 'Sun Valley',
    'region': 'North East Valley',
  },
  {
    'id': 10,
    'name': 'Sunland-Tujunga',
    'region': 'North East Valley',
  },
  {
    'id': 5,
    'name': 'Sylmar',
    'region': 'North East Valley',
  },
  {
    'id': 99,
    'name': 'Chatsworth',
    'region': 'North West Valley',
  },
  {
    'id': 4,
    'name': 'Granada Hills North',
    'region': 'North West Valley',
  },
  {
    'id': 118,
    'name': 'Granada Hills South',
    'region': 'North West Valley',
  },
  {
    'id': 111,
    'name': 'North Hills West',
    'region': 'North West Valley',
  },
  {
    'id': 120,
    'name': 'Northridge East',
    'region': 'North West Valley',
  },
  {
    'id': 124,
    'name': 'Northridge South',
    'region': 'North West Valley',
  },
  {
    'id': 113,
    'name': 'Northridge West',
    'region': 'North West Valley',
  },
  {
    'id': 114,
    'name': 'Porter Ranch',
    'region': 'North West Valley',
  },
  {
    'id': 13,
    'name': 'Canoga Park',
    'region': 'South West Valley',
  },
  {
    'id': 18,
    'name': 'Encino',
    'region': 'South West Valley',
  },
  {
    'id': 19,
    'name': 'Lake Balboa',
    'region': 'South West Valley',
  },
  {
    'id': 15,
    'name': 'Reseda',
    'region': 'South West Valley',
  },
  {
    'id': 17,
    'name': 'Tarzana',
    'region': 'South West Valley',
  },
  {
    'id': 11,
    'name': 'West Hills',
    'region': 'South West Valley',
  },
  {
    'id': 14,
    'name': 'Winnetka',
    'region': 'South West Valley',
  },
  {
    'id': 16,
    'name': 'Woodland Hills-Warner Center',
    'region': 'South West Valley',
  },
  {
    'id': 28,
    'name': 'Greater Toluca Lake',
    'region': 'South East Valley',
  },
  {
    'id': 21,
    'name': 'Greater Valley Glen',
    'region': 'South East Valley',
  },
  {
    'id': 24,
    'name': 'NoHo',
    'region': 'South East Valley',
  },
  {
    'id': 23,
    'name': 'North Hollywood Northeast',
    'region': 'South East Valley',
  },
  {
    'id': 22,
    'name': 'North Hollywood West',
    'region': 'South East Valley',
  },
  {
    'id': 26,
    'name': 'Sherman Oaks',
    'region': 'South East Valley',
  },
  {
    'id': 27,
    'name': 'Studio City',
    'region': 'South East Valley',
  },
  {
    'id': 25,
    'name': 'Valley Village',
    'region': 'South East Valley',
  },
  {
    'id': 20,
    'name': 'Van Nuys',
    'region': 'South East Valley',
  },
  {
    'id': 32,
    'name': 'Central Hollywood',
    'region': 'Central 1',
  },
  {
    'id': 34,
    'name': 'East Hollywood',
    'region': 'Central 1',
  },
  {
    'id': 119,
    'name': 'Greater Wilshire',
    'region': 'Central 1',
  },
  {
    'id': 29,
    'name': 'Hollywood Hills West',
    'region': 'Central 1',
  },
  {
    'id': 33,
    'name': 'Hollywood Studio District',
    'region': 'Central 1',
  },
  {
    'id': 30,
    'name': 'Hollywood United',
    'region': 'Central 1',
  },
  {
    'id': 58,
    'name': 'Mid City West',
    'region': 'Central 1',
  },
  {
    'id': 60,
    'name': 'PICO',
    'region': 'Central 1',
  },
  {
    'id': 52,
    'name': 'Downtown Los Angeles',
    'region': 'Central 2',
  },
  {
    'id': 46,
    'name': 'Historic Cultural',
    'region': 'Central 2',
  },
  {
    'id': 128,
    'name': 'Historic Cultural North',
    'region': 'Central 2',
  },
  {
    'id': 54,
    'name': 'MacArthur Park',
    'region': 'Central 2',
  },
  {
    'id': 104,
    'name': 'Olympic Park',
    'region': 'Central 2',
  },
  {
    'id': 76,
    'name': 'Pico Union',
    'region': 'Central 2',
  },
  {
    'id': 97,
    'name': 'Westlake North',
    'region': 'Central 2',
  },
  {
    'id': 121,
    'name': 'Westlake South',
    'region': 'Central 2',
  },
  {
    'id': 55,
    'name': 'Wilshire Center - Koreatown',
    'region': 'Central 2',
  },
  {
    'id': 37,
    'name': 'Atwater Village',
    'region': 'East',
  },
  {
    'id': 44,
    'name': 'Echo Park',
    'region': 'East',
  },
  {
    'id': 43,
    'name': 'Elysian Valley Riverside',
    'region': 'East',
  },
  {
    'id': 36,
    'name': 'Los Feliz',
    'region': 'East',
  },
  {
    'id': 53,
    'name': 'Rampart Village',
    'region': 'East',
  },
  {
    'id': 38,
    'name': 'Silver Lake',
    'region': 'East',
  },
  {
    'id': 42,
    'name': 'Arroyo Seco',
    'region': 'North East LA',
  },
  {
    'id': 50,
    'name': 'Boyle Heights',
    'region': 'North East LA',
  },
  {
    'id': 40,
    'name': 'Eagle Rock',
    'region': 'North East LA',
  },
  {
    'id': 39,
    'name': 'Glassell Park',
    'region': 'North East LA',
  },
  {
    'id': 102,
    'name': 'Greater Cypress Park',
    'region': 'North East LA',
  },
  {
    'id': 126,
    'name': 'Hermon',
    'region': 'North East LA',
  },
  {
    'id': 41,
    'name': 'Historic Highland Park',
    'region': 'North East LA',
  },
  {
    'id': 48,
    'name': 'LA-32',
    'region': 'North East LA',
  },
  {
    'id': 47,
    'name': 'Lincoln Heights',
    'region': 'North East LA',
  },
  {
    'id': 86,
    'name': 'CANNDU',
    'region': 'South LA 2',
  },
  {
    'id': 110,
    'name': 'Central Alameda',
    'region': 'South LA 2',
  },
  {
    'id': 87,
    'name': 'EC Southeast',
    'region': 'South LA 2',
  },
  {
    'id': 84,
    'name': 'EC Southwest',
    'region': 'South LA 2',
  },
  {
    'id': 78,
    'name': 'South Central',
    'region': 'South LA 2',
  },
  {
    'id': 123,
    'name': 'United For Victory',
    'region': 'South LA 2',
  },
  {
    'id': 109,
    'name': 'Voices Of 90037',
    'region': 'South LA 2',
  },
  {
    'id': 88,
    'name': 'Watts',
    'region': 'South LA 2',
  },
  {
    'id': 125,
    'name': 'Zapata King',
    'region': 'South LA 2',
  },
  {
    'id': 81,
    'name': 'EC Central',
    'region': 'South LA 1',
  },
  {
    'id': 77,
    'name': 'EC North',
    'region': 'South LA 1',
  },
  {
    'id': 79,
    'name': 'EC West',
    'region': 'South LA 1',
  },
  {
    'id': 73,
    'name': 'Mid City',
    'region': 'South LA 1',
  },
  {
    'id': 80,
    'name': 'Park Mesa Heights',
    'region': 'South LA 1',
  },
  {
    'id': 74,
    'name': 'United Neighborhoods',
    'region': 'South LA 1',
  },
  {
    'id': 75,
    'name': 'West Adams',
    'region': 'South LA 1',
  },
  {
    'id': 64,
    'name': 'Bel Air-Beverly Crest',
    'region': 'West LA',
  },
  {
    'id': 70,
    'name': 'Del Rey',
    'region': 'West LA',
  },
  {
    'id': 67,
    'name': 'Mar Vista',
    'region': 'West LA',
  },
  {
    'id': 127,
    'name': 'North Westwood',
    'region': 'West LA',
  },
  {
    'id': 115,
    'name': 'Palms',
    'region': 'West LA',
  },
  {
    'id': 61,
    'name': 'South Robertson',
    'region': 'West LA',
  },
  {
    'id': 68,
    'name': 'Venice',
    'region': 'West LA',
  },
  {
    'id': 71,
    'name': 'Westchester/Playa',
    'region': 'West LA',
  },
  {
    'id': 66,
    'name': 'West Los Angeles',
    'region': 'West LA',
  },
  {
    'id': 62,
    'name': 'Westside',
    'region': 'West LA',
  },
  {
    'id': 63,
    'name': 'Westwood',
    'region': 'West LA',
  },
  {
    'id': 95,
    'name': 'Central San Pedro',
    'region': 'Harbor',
  },
  {
    'id': 96,
    'name': 'Coastal San Pedro',
    'region': 'Harbor',
  },
  {
    'id': 92,
    'name': 'Harbor City',
    'region': 'Harbor',
  },
  {
    'id': 90,
    'name': 'Harbor Gateway North',
    'region': 'Harbor',
  },
  {
    'id': 91,
    'name': 'Harbor Gateway South',
    'region': 'Harbor',
  },
  {
    'id': 94,
    'name': 'Northwest San Pedro',
    'region': 'Harbor',
  },
  {
    'id': 93,
    'name': 'Wilmington',
    'region': 'Harbor',
  }]

In [13]:
short_names = pd.DataFrame(councils)

In [14]:
short_names.set_index(['id'], inplace=True)

In [15]:
short_names.head()

                         name             region
id
6                      Arleta  North East Valley
9    Foothill Trails District  North East Valley
101             Mission Hills  North East Valley
112          North Hills East  North East Valley
7                     Pacoima  North East Valley

In [16]:
unique = ncCurrent[~ncCurrent.index.isin(short_names.index)]
print(unique.name)

id
0    HISTORIC CULTURAL NORTH NC
0             NORTH WESTWOOD NC
Name: name, dtype: object

In [17]:
joined = ncCurrent.join(short_names, rsuffix="short")

In [18]:
joined.head()

,name,waddress,certified,objectid,service_re,nc_id,dwebsite,geometry,nameshort,region
id,,,,,,,,,,
0,HISTORIC CULTURAL NORTH NC,http://empowerla.org/HCNNC,2002-04-27T00:00:00,27,REGION 6 - CENTRAL 2,0,http://empowerla.org/HCNNC,"MULTIPOLYGON (((-118.23402 34.07851, -118.2339...",NaN,NaN
0,NORTH WESTWOOD NC,https://empowerla.org/nwwnc/,2010-01-19T00:00:00,105,REGION 11 - WEST LA,0,https://empowerla.org/nwwnc/,"MULTIPOLYGON (((-118.44576 34.05534, -118.4457...",NaN,NaN
4,GRANADA HILLS NORTH NC,http://ghnnc.org/,2002-09-10T00:00:00,74,REGION 2 - NORTH WEST VALLEY,4,http://empowerla.org/GHNNC,"MULTIPOLYGON (((-118.54092 34.29880, -118.5409...",Granada Hills North,North West Valley
5,SYLMAR NC,http://www.sylmarneighborhoodcouncil.org/,2003-05-06T00:00:00,45,REGION 1 - NORTH EAST VALLEY,5,http://empowerla.org/SNC,"MULTIPOLYGON (((-118.47401 34.29756, -118.4742...",Sylmar,North East Valley
6,ARLETA NC,http://www.arletanc.org/,2002-10-22T00:00:00,39,REGION 1 - NORTH EAST VALLEY,6,http://empowerla.org/ANC,"MULTIPOLYGON (((-118.44206 34.26475, -118.4418...",Arleta,North East Valley

In [20]:
joined.to_file("nc-boundary-2019-centroid.geojson", driver='GeoJSON')